// <auto-generated />
using System;
using LudoVault.Infra.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace LudoVault.Infra.Migrations
{
    [DbContext(typeof(MysqlContext))]
    partial class MysqlContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.14")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            MySqlModelBuilderExtensions.AutoIncrementColumns(modelBuilder);

            modelBuilder.Entity("LudoVault.Domain.Model.GameGenreModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("GameId")
                        .HasColumnType("int")
                        .HasColumnName("game_id");

                    b.Property<int>("GenreId")
                        .HasColumnType("int")
                        .HasColumnName("genre_id");

                    b.HasKey("Id");

                    b.HasIndex("GenreId");

                    b.HasIndex("GameId", "GenreId")
                        .IsUnique();

                    b.ToTable("game_genre", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            GameId = 1,
                            GenreId = 1
                        },
                        new
                        {
                            Id = 2,
                            GameId = 1,
                            GenreId = 2
                        },
                        new
                        {
                            Id = 3,
                            GameId = 1,
                            GenreId = 4
                        });
                });

            modelBuilder.Entity("LudoVault.Domain.Model.GameModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("DATETIME")
                        .HasColumnName("created_at");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(1500)
                        .IsUnicode(true)
                        .HasColumnType("varchar(1500)")
                        .HasColumnName("description");

                    b.Property<string>("ImageUrl")
                        .IsRequired()
                        .HasMaxLength(255)
                        .IsUnicode(false)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("image_url");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .IsUnicode(true)
                        .HasColumnType("varchar(200)")
                        .HasColumnName("name");

                    b.Property<int>("PublisherId")
                        .HasColumnType("int")
                        .HasColumnName("publisher_id");

                    b.HasKey("Id");

                    b.HasIndex("PublisherId");

                    b.ToTable("game", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Estados Unidos, 1899. Arthur Morgan e a gangue Van der Linde são forçados a fugir. Com agentes federais e os melhores caçadores de recompensas no seu encalço, a gangue precisa roubar, assaltar e lutar para sobreviver no impiedoso coração dos Estados Unidos. Conforme divisões internas profundas ameaçam despedaçar a gangue, Arthur deve fazer uma escolha entre os seus próprios ideais e a lealdade à gangue que o criou.",
                            ImageUrl = "/uploads/games/default-image.webp",
                            Name = "Red Dead Redemption 2",
                            PublisherId = 1
                        });
                });

            modelBuilder.Entity("LudoVault.Domain.Model.GamePlatformModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("GameId")
                        .HasColumnType("int")
                        .HasColumnName("game_id");

                    b.Property<int>("PlatformId")
                        .HasColumnType("int")
                        .HasColumnName("platform_id");

                    b.HasKey("Id");

                    b.HasIndex("PlatformId");

                    b.HasIndex("GameId", "PlatformId")
                        .IsUnique();

                    b.ToTable("game_platform", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            GameId = 1,
                            PlatformId = 1
                        },
                        new
                        {
                            Id = 2,
                            GameId = 1,
                            PlatformId = 2
                        },
                        new
                        {
                            Id = 3,
                            GameId = 1,
                            PlatformId = 3
                        });
                });

            modelBuilder.Entity("LudoVault.Domain.Model.GenreModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(20)
                        .IsUnicode(false)
                        .HasColumnType("varchar(20)")
                        .HasColumnName("name");

                    b.HasKey("Id");

                    b.ToTable("genre", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Ação"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Aventura"
                        },
                        new
                        {
                            Id = 3,
                            Name = "RPG"
                        },
                        new
                        {
                            Id = 4,
                            Name = "Mundo Aberto"
                        });
                });

            modelBuilder.Entity("LudoVault.Domain.Model.PlatformModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(30)
                        .IsUnicode(false)
                        .HasColumnType("varchar(30)")
                        .HasColumnName("name");

                    b.HasKey("Id");

                    b.ToTable("platform", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "PlayStation 4"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Xbox One"
                        },
                        new
                        {
                            Id = 3,
                            Name = "PC"
                        });
                });

            modelBuilder.Entity("LudoVault.Domain.Model.PublisherModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(60)
                        .IsUnicode(false)
                        .HasColumnType("varchar(60)")
                        .HasColumnName("name");

                    b.HasKey("Id");

                    b.ToTable("publisher", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Rockstar Games"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Nintendo"
                        },
                        new
                        {
                            Id = 3,
                            Name = "Sony Interactive"
                        });
                });

            modelBuilder.Entity("LudoVault.Domain.Model.RatingModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Comment")
                        .IsRequired()
                        .HasMaxLength(1200)
                        .IsUnicode(true)
                        .HasColumnType("varchar(1200)")
                        .HasColumnName("comment");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("DATETIME")
                        .HasColumnName("created_at");

                    b.Property<int>("GameId")
                        .HasColumnType("int")
                        .HasColumnName("game_id");

                    b.Property<decimal>("Rating")
                        .HasPrecision(2, 1)
                        .HasColumnType("decimal(2,1)")
                        .HasColumnName("rating");

                    b.Property<int>("UserId")
                        .HasColumnType("int")
                        .HasColumnName("user_id");

                    b.HasKey("Id");

                    b.HasIndex("GameId");

                    b.HasIndex("UserId");

                    b.ToTable("rating", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Comment = "Uma verdadeira obra prima dos videogames!",
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            GameId = 1,
                            Rating = 5.0m,
                            UserId = 1
                        });
                });

            modelBuilder.Entity("LudoVault.Domain.Model.UserLibraryModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("AddedAt")
                        .HasColumnType("DATETIME")
                        .HasColumnName("added_at");

                    b.Property<int>("GameId")
                        .HasColumnType("int")
                        .HasColumnName("game_id");

                    b.Property<int>("UserId")
                        .HasColumnType("int")
                        .HasColumnName("user_id");

                    b.HasKey("Id");

                    b.HasIndex("GameId");

                    b.HasIndex("UserId", "GameId")
                        .IsUnique();

                    b.ToTable("user_library", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            AddedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            GameId = 1,
                            UserId = 1
                        });
                });

            modelBuilder.Entity("LudoVault.Domain.Model.UserListItemModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("AddedAt")
                        .HasColumnType("DATETIME")
                        .HasColumnName("added_at");

                    b.Property<int>("GameId")
                        .HasColumnType("int")
                        .HasColumnName("game_id");

                    b.Property<int>("ListId")
                        .HasColumnType("int")
                        .HasColumnName("list_id");

                    b.HasKey("Id");

                    b.HasIndex("GameId");

                    b.HasIndex("ListId");

                    b.ToTable("user_list_game", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            AddedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            GameId = 1,
                            ListId = 1
                        });
                });

            modelBuilder.Entity("LudoVault.Domain.Model.UserListModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("DATETIME")
                        .HasColumnName("created_at");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(60)
                        .IsUnicode(true)
                        .HasColumnType("varchar(60)")
                        .HasColumnName("name");

                    b.Property<int>("UserId")
                        .HasColumnType("int")
                        .HasColumnName("user_id");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("user_list", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Meus Jogos Favoritos",
                            UserId = 1
                        });
                });

            modelBuilder.Entity("LudoVault.Domain.Model.UserModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("AvatarUrl")
                        .IsRequired()
                        .HasMaxLength(255)
                        .IsUnicode(false)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("avatar_url");

                    b.Property<string>("Bio")
                        .HasMaxLength(1200)
                        .IsUnicode(true)
                        .HasColumnType("varchar(1200)")
                        .HasColumnName("bio");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("DATETIME")
                        .HasColumnName("created_at");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(100)
                        .IsUnicode(false)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("email");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .IsUnicode(false)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("name");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasMaxLength(255)
                        .IsUnicode(false)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("password_hash");

                    b.HasKey("Id");

                    b.ToTable("user", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            AvatarUrl = "/uploads/users/default-image.webp",
                            Bio = "Bem vindos ao meu perfil!",
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "cristof@gmail.com",
                            Name = "Cristofer",
                            PasswordHash = "$2a$12$Ih3ZGAGY3KX9AQ6hJFfhL.NdBsGN0TonaaIPigkVBpb.VDN9aXuj2"
                        });
                });

            modelBuilder.Entity("LudoVault.Domain.Model.GameGenreModel", b =>
                {
                    b.HasOne("LudoVault.Domain.Model.GameModel", "Game")
                        .WithMany("GameGenres")
                        .HasForeignKey("GameId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_game_genre_game");

                    b.HasOne("LudoVault.Domain.Model.GenreModel", "Genre")
                        .WithMany("GameGenres")
                        .HasForeignKey("GenreId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_game_genre_genre");

                    b.Navigation("Game");

                    b.Navigation("Genre");
                });

            modelBuilder.Entity("LudoVault.Domain.Model.GameModel", b =>
                {
                    b.HasOne("LudoVault.Domain.Model.PublisherModel", "Publisher")
                        .WithMany("Games")
                        .HasForeignKey("PublisherId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("FK_game_publisher");

                    b.Navigation("Publisher");
                });

            modelBuilder.Entity("LudoVault.Domain.Model.GamePlatformModel", b =>
                {
                    b.HasOne("LudoVault.Domain.Model.GameModel", "Game")
                        .WithMany("GamePlatforms")
                        .HasForeignKey("GameId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_game_platform_game");

                    b.HasOne("LudoVault.Domain.Model.PlatformModel", "Platform")
                        .WithMany("GamePlatforms")
                        .HasForeignKey("PlatformId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_game_platform_platform");

                    b.Navigation("Game");

                    b.Navigation("Platform");
                });

            modelBuilder.Entity("LudoVault.Domain.Model.RatingModel", b =>
                {
                    b.HasOne("LudoVault.Domain.Model.GameModel", "Game")
                        .WithMany("GameRatings")
                        .HasForeignKey("GameId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_rating_game");

                    b.HasOne("LudoVault.Domain.Model.UserModel", "User")
                        .WithMany("Ratings")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_rating_user");

                    b.Navigation("Game");

                    b.Navigation("User");
                });

            modelBuilder.Entity("LudoVault.Domain.Model.UserLibraryModel", b =>
                {
                    b.HasOne("LudoVault.Domain.Model.GameModel", "Game")
                        .WithMany("UserLibraries")
                        .HasForeignKey("GameId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("FK_user_library_game");

                    b.HasOne("LudoVault.Domain.Model.UserModel", "User")
                        .WithMany("UserLibraries")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_user_library_user");

                    b.Navigation("Game");

                    b.Navigation("User");
                });

            modelBuilder.Entity("LudoVault.Domain.Model.UserListItemModel", b =>
                {
                    b.HasOne("LudoVault.Domain.Model.GameModel", "Game")
                        .WithMany("ListItems")
                        .HasForeignKey("GameId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("FK_list_item_game");

                    b.HasOne("LudoVault.Domain.Model.UserListModel", "UserList")
                        .WithMany("ListItems")
                        .HasForeignKey("ListId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_list_item_list");

                    b.Navigation("Game");

                    b.Navigation("UserList");
                });

            modelBuilder.Entity("LudoVault.Domain.Model.UserListModel", b =>
                {
                    b.HasOne("LudoVault.Domain.Model.UserModel", "User")
                        .WithMany("Lists")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_user_list_user");

                    b.Navigation("User");
                });

            modelBuilder.Entity("LudoVault.Domain.Model.GameModel", b =>
                {
                    b.Navigation("GameGenres");

                    b.Navigation("GamePlatforms");

                    b.Navigation("GameRatings");

                    b.Navigation("ListItems");

                    b.Navigation("UserLibraries");
                });

            modelBuilder.Entity("LudoVault.Domain.Model.GenreModel", b =>
                {
                    b.Navigation("GameGenres");
                });

            modelBuilder.Entity("LudoVault.Domain.Model.PlatformModel", b =>
                {
                    b.Navigation("GamePlatforms");
                });

            modelBuilder.Entity("LudoVault.Domain.Model.PublisherModel", b =>
                {
                    b.Navigation("Games");
                });

            modelBuilder.Entity("LudoVault.Domain.Model.UserListModel", b =>
                {
                    b.Navigation("ListItems");
                });

            modelBuilder.Entity("LudoVault.Domain.Model.UserModel", b =>
                {
                    b.Navigation("Lists");

                    b.Navigation("Ratings");

                    b.Navigation("UserLibraries");
                });
#pragma warning restore 612, 618
        }
    }
}
